/*game_levels.js
 *This file design the game_level in grids(arrays of strings),
 *including background,actors,and restricted area that player
 *could not enter in. Each letter in the string stands for some 
 *background tile or actor.For example, "g" in background
 *stands for grass block,"b" in actors stands for 
 *blue gem."r" in restArea means the area that player
 *could not enter in.
*/


var GAME_LEVELS = [{
    background: [
        "ggggggg",
        "ggfoegg",
        "ggbbbgg",
        "gctmtcg",
        "ddddddd",
        "ddddddd",
        "ddddddd",
        "hhhhhhh",
        "hhhhhhh",
        "ggggggg",
        "ggggggg",
        "ggggggg",
        "ddddddd",
        "ddddddd",
        "ggggggg",
        "ggggggg",
        "ggggggg",
        "hhddhhh",
        "hhddhhh",
        "ggggggg",
        "ggggggg",
        "ggggggg",
        "ggggggg",
        "ggggggg",
    ],
    actors: [
        "      k",
        "       ",
        "       ",
        "       ",
        " g     ",
        "       ",
        "      b",
        "tt     ",
        "     TT",
        "      b",
        "o      ",
        "       ",
        "ee   e ",
        " E   EE",
        " g     ",
        "     b ",
        "       ",
        "       ",
        "       ",
        " b     ",
        "      o",
        "       ",
        "   c   ",
        "       "
    ],
    restArea:[
        "       ",
        "  rrr  ",
        "  rrr  ",
        " rrrrr ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       "
    ]
}, {
    background: [
        "ggggggg",
        "ggfoegg",
        "ggbbbgg",
        "gctmtcg",
        "ddddddd",
        "ddddddd",
        "ddddddd",
        "hhhhhdh",
        "hhhhhdh",
        "ggggggg",
        "ggggggg",
        "ggggggg",
        "ddddddd",
        "ddddddd",
        "ggggggg",
        "ggggggg",
        "ggggggg",
        "dhhhhhh",
        "dhhhhhh",
        "ggggggg",
        "ggggggg",
        "ggggggg",
        "ggggggg",
        "ggggggg",
    ],
    actors: [
        "       ",
        " k     ",
        "       ",
        "       ",
        " g    b",
        "U      ",
        "      u",
        "       ",
        "       ",
        "     gb",
        "      o",
        "       ",
        "AA     ",
        "     aa",
        "bg     ",
        "o      ",
        "       ",
        "       ",
        "       ",
        "    ogb",
        "    bgo",
        "       ",
        "   c   ",
        "       "
    ],
    restArea:[
        "       ",
        "  rrr  ",
        "  rrr  ",
        " rrrrr ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       ",
        "       "
    ]
}];