var GAME_LEVELS=[
{background:["ggggggg",
			 "ggogggg",
			 "rorrrrr",
			 "rrrorrr",
			 "gghhgog",
			 "gghggog",
             "ggggggg",
             "rrrrrrr",
             "ggggggg",
             "rrrrrrr",
             "ggggggg"],
actors:["       ",
		"   -   ",
		"k      ",
		" -  -  ",
		" g     ",
		"      b",
        "       ",
        "       ",
        "       ",
        "      c",
        "       "]

},
    {background:["rrrrrrr",
			 "ggogggg",
			 "rorrrrr",
			 "ggggggg",
			 "gghhgog",
			 "gghggog"],
actors:["       ",
		"   -   ",
		"k     o",
		"    -  ",
		"    g  ",
		"c      "]}
];