var GAME_LEVELS=[
{background:["sssssss",
			 "ggggggg",
			 "rrrrrrr",
			 "rrrrrrr",
			 "gghhghg",
			 "gghgghg",
             "ghggghg",
             "ggggggg",
             "ggggggg",
             "rrrrrrr",
             "ggggggg"],
actors:["       ",
		"   -   ",
		"k      ",
		" -  -  ",
		" g     ",
		"      b",
        "---    ",
        "    ===",
        "  c    ",
        "       ",
        "       "]

},
    {background:["rrrrrrr",
			 "ggogggg",
			 "rorrrrr",
			 "ggggggg",
			 "gghhgog",
			 "gghggog"],
actors:["       ",
		"   -   ",
		"k     o",
		"    -  ",
		"    g  ",
		"c      "]}
];